# Generated by Django 3.2.5 on 2021-07-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210727_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='trail_difficulty',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='trail_type',
        ),
    ]
