# Generated by Django 3.2.5 on 2021-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210727_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='route_type',
            field=models.CharField(choices=[('LO', 'Loop'), ('OB', 'Out And Back'), ('PP', 'Point to Point')], default='LO', max_length=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='trail_difficulty',
            field=models.CharField(choices=[('BR', 'Breeze'), ('EZ', 'Easy'), ('IN', 'Intermediate'), ('HA', 'Hard'), ('EX', 'Extreme')], default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='trail_type',
            field=models.CharField(choices=[('DT', 'Day trail'), ('SP', 'Slack pack'), ('BP', 'Backpack'), ('LD', 'Long distance'), ('WN', 'Wilderness'), ('BC', 'Basecamp')], default='DT', max_length=2),
        ),
    ]
