# Generated by Django 3.2.5 on 2021-07-27 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210727_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='accommodation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location_pin',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pertinent_info',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
