# Generated by Django 3.2.5 on 2021-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_owners_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.CharField(choices=[('GA', 'Gauteng'), ('FS', 'Free State'), ('KN', 'KwaZulu-Natal'), ('WC', 'Western Cape'), ('NC', 'Northern Cape'), ('EC', 'Eastern Cape'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NW', 'North West')], default='GA', max_length=2),
        ),
    ]
