# Generated by Django 3.2.5 on 2021-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_listing_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='elevation_gain',
            field=models.IntegerField(blank=True),
        ),
    ]
