# Generated by Django 3.2.5 on 2021-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_listing_elevation_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.CharField(choices=[('NU', '<-- Select Province -->'), ('GA', 'Gauteng'), ('FS', 'Free State'), ('KN', 'KwaZulu-Natal'), ('WC', 'Western Cape'), ('NC', 'Northern Cape'), ('EC', 'Eastern Cape'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NW', 'North West')], default='NU', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='route_type',
            field=models.CharField(choices=[('NU', '<-- Select Type -->'), ('LO', 'Loop'), ('OB', 'Out And Back'), ('PP', 'Point to Point')], default='NU', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='trail_difficulty',
            field=models.CharField(choices=[('NU', '<-- Select Difficulty -->'), ('BR', 'Breeze'), ('EZ', 'Easy'), ('IN', 'Intermediate'), ('HA', 'Hard'), ('EX', 'Extreme')], default='NU', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='trail_type',
            field=models.CharField(choices=[('NU', '<-- Select Type -->'), ('DT', 'Day trail'), ('SP', 'Slack pack'), ('BP', 'Backpack'), ('LD', 'Long distance'), ('WN', 'Wilderness'), ('BC', 'Basecamp')], default='NU', max_length=2),
        ),
    ]
