# Generated by Django 3.2.5 on 2021-07-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210728_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='premium_expiry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
