# Generated by Django 3.2.5 on 2021-07-29 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='UserTrailLinking',
        ),
    ]
