# Generated by Django 3.2.5 on 2021-08-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210729_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='trail_length',
            field=models.FloatField(),
        ),
    ]
