# Generated by Django 3.2.5 on 2021-08-02 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_claim_claim_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_token',
            field=models.IntegerField(default=913734),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 12, 44, 10, 619057)),
        ),
    ]
