# Generated by Django 3.2.5 on 2021-08-02 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_claim_claim_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 22, 51, 380260)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_token',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
