# Generated by Django 3.2.5 on 2021-08-03 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_claim_claim_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 12, 33, 41, 136773, tzinfo=utc)),
        ),
    ]
