# Generated by Django 3.2.5 on 2021-08-05 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210805_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 10, 4, 55, 76040, tzinfo=utc)),
        ),
    ]
