# Generated by Django 3.2.5 on 2021-08-05 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_alter_claim_claim_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField()),
                ('total', models.IntegerField()),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 11, 36, 5, 76795, tzinfo=utc))),
                ('paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 11, 36, 5, 76795, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='InvoiceTrailLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
            ],
            options={
                'unique_together': {('invoice', 'trail')},
                'index_together': {('invoice', 'trail')},
            },
        ),
    ]
