# Generated by Django 3.2.5 on 2021-08-05 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210805_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_url',
            field=models.ImageField(blank=True, upload_to='invoice/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trails',
            field=models.TextField(default='Not Supplied'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 11, 42, 31, 842542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 11, 42, 31, 842542, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='InvoiceTrailLinking',
        ),
    ]
