# Generated by Django 3.2.5 on 2021-08-05 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210805_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 11, 43, 44, 688640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 11, 43, 44, 688640, tzinfo=utc)),
        ),
    ]
